# -*- coding: utf-8 -*-
"""ML MODELIN (PCCI) 08/2025

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-a6FqyI6V98DD9xU1HdXtfWkX6gK_S6A

##READMISSION FLAG INDICATOR AI/ML

#Importing DataSet
"""

#Code Snippet 1
#Installing pycaret For ML modeling
!pip install -U --pre pycaret

#Code Snippet 2
#Import Pandas
import pandas as pd

#importing Dataset
data=pd.read_csv('https://raw.githubusercontent.com/nvamsimohan/DallasDSA/main/PCCI%20Cases%20Readmit30%20Data.csv')

#Displaying the Data
data

#code Snippet 3
#displaying column
data.dtypes

"""#AI/ML Model Testing Process"""

#Code Snippet 4
#importing pycare regression modules
from pycaret.classification import *

#Code Snippet 5
#Setting the target Variables
y = 'Readmit30'

#Setting ignored Varibles(noise varibles missing more thant 20%)
ignored_cols= [ 'Admit_Week', 'Admit_Month','Temperature', 'Weight', 'Height']

# Code snippet 7
# Setting the categorical variables
cat_cols = ['Care_Plan_Following_Discharge', 'Insurance_Provider', 'Gender', 'Condition', 'Marital_Status','Tobacco_User', 'Depression', 'ICU', 'Drug_Abuse','Mood_Disorder', 'Diabetes', 'Anxiety', 'Dementia','Obesity']

# Code snippet 7
# Setting the numerical PREDICTOR variables
num_cols = ['Chronic_Conditions', 'Pat_Pain_Score','Pulse',
       'ER_Visits', 'IP_Visits','Age','Cost_Of_Initial_Stay','Glucose','Bmi']

# Code snippet 8
# Setting up/configuring the pycaret setup for ML modeling
classification_setup = setup(data,
                        target = y,
                        ignore_features = ignored_cols,
                        categorical_features = cat_cols,
                        numeric_features = num_cols, train_size = 0.7)

"""#Compare ML models"""

#Code Snippet 9
#Run Pycare For ML Modeling
compare_models()

"""#Best Model"""

# Code snippet 10
# Building the model with the best algorithm
best_model = create_model('rf')

# Code snippet 11
# Predicting standard scores on a dataset
predictions = predict_model(best_model, data)

# Code snippet 12
# Exporting predictions to a csv file
predictions.to_csv('PCCI Readmition Status predictions RF model.csv')

"""#Model Visuals"""

# Code Snippet 13
# Plot the confusion matrix for the Best Model
plot_model(best_model, plot="confusion_matrix")

# Code Snippet 14
# Plot the ROC curve (AUC) for the Best Model
plot_model(best_model, plot="auc")

# Code Snippet 15
# Plot the Precision-Recall curve
plot_model(best_model, plot="pr")

# Code Snippet 16
# Plot the class prediction error
plot_model(best_model, plot="error")

# Code Snippet 17
# Plot the learning curve
plot_model(best_model, plot="learning")

# Code Snippet 18
# Plot the calibration curve
plot_model(best_model, plot="calibration")

