# -*- coding: utf-8 -*-
"""PCCI Anomaly Detection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10-FIpgXVL_YmMcLsUFAtdk1jOexBdcap

##**PCCI ANOMALY DETECTION WITH PYOD**

#IMPORTING PYOD AND DATA SET
"""

#code snippet 1
#Installing pyod package for anormaly detection algorithms (knn)
!pip install pyod

#code snippet 2
#Importing pyod
from pyod.models.knn import KNN

# Code snippet 3
# Importing the dataset
import pandas as pd
data = pd.read_csv('https://raw.githubusercontent.com/nvamsimohan/DallasDSA/main/PCCI%20Cases%20Readmit30%20Data.csv')


data

# Code snippet 4
# Create new dataset with only numerical columns
numeric_dataset = data.select_dtypes(include=['float64', 'int64'])
numeric_dataset

# Code snippet 5
# Training with the KNN algorithm to identify the anomalies
ad_model = KNN()

# Handle missing values by imputing with the mean
numeric_dataset_cleaned = numeric_dataset.fillna(numeric_dataset.mean())

ad_model.fit(numeric_dataset_cleaned)

# Code snippet 6
#Predict anomalies (1 = normal, -1 = Anomaly)
anomaly_labels = ad_model.labels_
anomaly_scores = ad_model.decision_scores_

"""#ADDING LABEL TO ANOMALY LABEL AND SCORE

"""

# Code snippet 7
# Adding the anomaly results to the original dataframe
data['Anomaly_Label'] = anomaly_labels
data['Anomaly_Score'] = anomaly_scores
data

"""#IMPORTING DATA SET WITH ANOMALY COLUMNS"""

# Code snippet 8
# Exporting the dataset to a csv file with anomaly info
data.to_csv('PCCI_KNN_Anomalies.csv', index=False)

"""#TOTAL COUNT OF ANOMALY ON DATASET"""

# Code snippet 9
# Displaying the number of anomalies
num_anomalies = (data['Anomaly_Label'] == 1).sum()
print(f"Number of anomalies: {num_anomalies}")